# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 110bc19aa7aab82446114fa2c1b1e6937d13cc2cec15d86f5fd15f402f62eb4ecdea09b6d9d66cac844db843fd55ea2f92dccbd9d198b08e909a6b4f37a353d3

test:
  secret_key_base: a4b3bc2be5334363d8f92f02e87237165f9abfd6b4eca777241f4ced5bf921a126b7b288a1d8f51c7452d44f596a419e20ee0ec166df08fecba411466a47937c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
